#!/bin/sh
#
# MIT License
#
# Copyright (c) 2017 Mikolaj Biel
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


#=== FUNCTION ======================================================
# NAME: show_help
# DESC: Dispatch help function
#   $1: [COMMAND] to show option for
#===================================================================
show_help() {
    if [ $# = 0 ]; then
        show_general_help
        exit 0
    fi
    case $1 in
        ls|list)
            show_list_help
            ;;
        rm|delete)
            show_delete_help
            ;;
        init)
            show_init_help
            ;;
        init-server)
            show_init_server_help
            ;;
        *)
            show_general_help
            exit 1
            ;;
    esac
}

#=== FUNCTION ======================================================
# NAME: show_general_help
# DESC: Show general help message
#===================================================================
show_general_help() {

    echo "\
Usage: $0 user@hostname COMMAND [OPTION]
    or $0 --help [COMMAND]

List of available commands:
     list, ls       List repository from the server
     delete, rm     Delete repository from the server
     init           Init git repository on the server
     init-server    Init git-related directories and files on the server"
}

#=== FUNCTION ======================================================
# NAME: show_list_help
# DESC: Show list help message
#===================================================================
show_list_help() {

    echo "\
Usage: $0 user@hostname list

List user's repositories"
}

#=== FUNCTION ======================================================
# NAME: show_delete_help
# DESC: Show delete help message
#===================================================================
show_delete_help() {

    echo "\
Usage: $0 user@hostname delete REPOSITORY_NAME

Delete git repository on the server"
}

#=== FUNCTION ======================================================
# NAME: show_init_server_help
# DESC: Show init-server help message
#===================================================================
show_init_server_help() {

    echo "\
Usage: $0 user@hostname init-server

Init git-related directories and files on the server"
}

#=== FUNCTION ======================================================
# NAME: show_init_help
# DESC: Show init help message
#===================================================================
show_init_help() {

    echo "\
Usage: $0 user@hostname init REPOSITORY_NAME

Init git repository on the server" 
}


#=== FUNCTION ======================================================
# NAME: init_server
# DESC: Init git-related directories and files on the server
#   $1: remote username
#   $2: remote server
#===================================================================
init_server() {

HTACCESS="\
# index files order
DirectoryIndex index.py index.php index.html index.htm

# git
SetEnv GIT_PROJECT_ROOT ~/git
SetEnv GIT_HTTP_EXPORT_ALL

RewriteEngine  on
RewriteBase /~$1/
RewriteRule ^git/(([a-zA-Z0-9._-]*.git/(HEAD|info/refs|objects/(info/[^/]+|[0-9a-f]{2}/[0-9a-f]{38}|pack/pack-[0-9a-f]{40}.(pack|idx))|git-(upload|receive)-pack)))$ __git/git.cgi/\\\$1
RewriteRule ^git/?$ __git/
RewriteRule ^git/(([a-zA-Z0-9._-]+/?)+)$ __git/repository_info.py

# python cgi
AddHandler cgi-script .py\
"

GIT_HTACCESS="\
IndexIgnore *\
"

GIT_CGI="\
#!/bin/sh

PATH_TRANSLATED=~/git/\\\${PATH_TRANSLATED:24}

PATH=~/git/:\\\$PATH
git http-backend \\\"\\\$@\\\"\
"

WEBAPP_CSS="
body {
    margin: 20px auto;
    max-width: 650px;
    line-height: 1.6;
    font-size: 18px;
    color: #587188;
    padding: 0 10px;
}

* {
    font-family: monospace;
}

ul, li {
    margin: 0;
    padding: 0;
}

li {
    display: block;
    list-style: none;
}

li span,
header span {
    display: inline-block;
    width: 3em;
}

li input,
header input {
    font-size: 16px;
    padding: 2px;
    width: calc(100% - 4.5em);
}

ul.repositories li {
    padding: 1em;
    margin-bottom: .4em;
}

ul.tree li {
    margin-bottom: .2em;
}

ul.tree li a {
    display: block;
    padding: .3em .6em;
    text-decoration: none;
}

ul.tree li:hover,
header {
    background-color: #dce8f5 !important;
}

ul.repositories li,
ul.tree.directories li {
    background-color: #ebf2fa;
}

h2 {
    margin: 0;
    padding: 0;
}

li > div:first-of-type {
   margin-bottom: 2px;
}

header {
   padding: 1em;
   margin-bottom: .2em;
}

footer {
    font-size: .7em;
    text-align: right;
}

a {
    color: #587188;
}

a:hover {
    color: #2e3a46;
}
"

WEBAPP_CODE_CSS="\
body {
     max-width: 1200px;
}

code {
     font-size: 14px;
}
td.hljs-ln-numbers {
    text-align: center;
    color: #ccc;
    border-right: 1px solid #999;
    vertical-align: top;
    padding-right: 5px;

    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
td.hljs-ln-code {
    padding-left: 10px;
}

code {
    white-space: pre-wrap;
    overflow: auto;
}

pre > code div {
    white-space: pre-wrap;
}
"

WEBAPP_INDEX="\
#!/usr/bin/python
import os

def get_ssh_link(name):
    return 'ssh://$1@$2/~/git/%s.git' % name

def get_http_link(name):
    return 'http://$2/~$1/git/%s.git' % name

def print_header():
    print '''
    <html><head>
    <title>$1's git repositories</title>
    <style>$WEBAPP_CSS</style>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    </head><body><ul class=\'repositories\'>
    '''

def print_repository(dir_name):
    name = dir_name[:-4]
    print '''
    <li>
        <h2>%s</h2>
        <div><span>ssh:</span> <input value='%s' readonly=true onClick='this.select();' /></div>
        <div><span>http:</span> <input value='%s' readonly=true onClick='this.select();' /></div>
    </li>
    ''' % (name, get_ssh_link(name), get_http_link(name))

def print_empty():
    print '''
    <li>
        <h2>there are no repositories ):</h2>
        <div>start working on something!</div>
    </li>
    '''

def print_footer():
    print '''
    </ul>
    <footer>powered by <a href='https://github.com/klausweiss/agh-git/'>agh-git</a></footer>
    </body>
    </html>
    '''

home = os.path.expanduser('~')
repositories = [dir for dir
                in next(os.walk('%s/git' % home))[1]
                if dir.endswith('.git')]

print 'Content-type: text/html\n\n'
print_header()
for repo in sorted(repositories, key=lambda dir: os.stat(dir).st_mtime, reverse=True):
    print_repository(repo)
if not repositories:
    print_empty()
print_footer()
"

WEBAPP_REPO="\
#!/usr/bin/python
import os
import shlex
import subprocess as sp


# ########################################################################## git


def sh(command, cwd=None, lines=True):
    output = sp.Popen(shlex.split(command), stdout=sp.PIPE,
                      stderr=sp.PIPE, cwd=cwd).communicate()[0]
    if lines:
        return output.split('\n')[:-1]
    else:
        return output


def list_branches(cwd=None):
    return [branch[2:] for branch in sorted(sh('git branch', cwd), reverse=True)]


def ls_tree(branch, path='', cwd=None):
    if path:
        path += '/'
    return [(item[1] == 'tree', item[3])
            for item
            in [rawItem.split() for rawItem in sh('git ls-tree %s %s' % (branch, path), cwd=cwd)]]


def get_object_hash(branch, path, cwd=None):
    return sh('git ls-tree %s %s' % (branch, path), cwd=cwd)[0].split()[2]


def file_contents(branch, path, cwd=None):
    object_hash = get_object_hash(branch, path, cwd)
    return sh('git cat-file -p %s' % object_hash, cwd=cwd, lines=False)


def is_dir(branch, path, cwd=None):
    return sh('git ls-tree %s %s' % (branch, path.strip('/')), cwd=cwd)[0].split()[1] == 'tree'


# ########################################################################## rendering


def get_ssh_link(name):
    return 'ssh://$1@$2/~/git/%s.git' % name

def get_http_link_base(name):
    return 'http://$2/~$1/git/%s' % name

def get_http_link(name):
    return 'http://$2/~$1/git/%s.git' % name

def title(requested_object, branch, repository_name):
    if requested_object:
        return '%s @ %s (%s at $1\'s git)' % (requested_object, branch, repository_name)
    elif not branch:
        return '%s at $1\'s git' % repository_name
    else:
        return '%s@%s at $1\'s git' % (branch, repository_name)

def print_header(requested_object, branch, repository_name):
    print ('''
    <html><head>
    <title>'''
    + title(requested_object, branch, repository_name) +
    '''</title>
    <style>$WEBAPP_CSS</style>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    </head><body>
    ''')

def print_footer():
    print '''
    <footer>powered by <a href='https://github.com/klausweiss/agh-git/'>agh-git</a></footer>
    </body>
    </html>
    '''

def print_tree_or_file(basepath, branch, requested_object, repository_name):
    try:
        if branch is None:
            branch = list_branches(basepath)[0]

        if is_dir(branch, requested_object, basepath) or not requested_object:
            print_tree(basepath, branch, requested_object, repository_name)
        else:
            print_file(basepath, branch, requested_object, repository_name)
    except Exception as e:
        print_error(e)

def print_tree(basepath, branch, path, repository_name):
    tree = ls_tree(branch, path, basepath)
    directories = sorted([name for is_dir, name in tree if is_dir])
    files = sorted([name for is_dir, name in tree if not is_dir])
    list_directories(directories, branch, path, repository_name)
    list_files(files, branch, repository_name)

def list_directories(directories, branch, path, repository_name):
    print '<ul class=\'tree directories\'>'
    if path:
        link = '%s/%s/%s/..' % (get_http_link_base(repository_name), branch, path.strip('/'))
        print '<li><a href=\'%s\'>..</a></li>' % link
    for dir in directories:
        link = '%s/%s/%s' % (get_http_link_base(repository_name), branch, dir)
        print '<li><a href=\'%s\'>%s</a></li>' % (link, dir)
    print '</ul>'

def list_files(files, branch, repository_name):
    print '<ul class=\'tree files\'>'
    for file in files:
        link = '%s/%s/%s' % (get_http_link_base(repository_name), branch, file)
        print '<li><a href=\'%s\'>%s</a></li>' % (link, file)
    print '</ul>'


def print_file(basepath, branch, path, repository_name):
    contents = file_contents(branch, path, basepath)
    print '''<style>$WEBAPP_CODE_CSS</style>'''
    print '<pre><code>%s</code></pre>' % contents
    print_js_libraries()

def print_js_libraries():
    print '''
          <link rel=\'stylesheet\' href=\'//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/default.min.css\'>
          <script src=\'//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js\'></script>
          <script src=\'//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.1.0/highlightjs-line-numbers.min.js\'></script>
          <script>hljs.initHighlightingOnLoad();hljs.initLineNumbersOnLoad();</script>
          <!-- custom languages -->
          <!-- haskell -->
          <script src=\'//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/haskell.min.js\'></script>
          '''

def print_error(e):
    print e

def print_repo_header(branch, repository_name):
    print '''
    <header>
        <h2>%s</h2>
        <div><span>ssh:</span> <input value='%s' readonly=true onClick='this.select();' /></div>
        <div><span>http:</span> <input value='%s' readonly=true onClick='this.select();' /></div>
    </header>
    ''' % (repository_name, get_ssh_link(repository_name), get_http_link(repository_name))

request_uri = os.environ.get('REQUEST_URI')
repository_name = request_uri.split('/')[3]
branch = request_uri.count('/') > 3 and request_uri.split('/')[4] or None
requested_object = '/'.join(request_uri.split('/')[5:])

home = os.path.expanduser('~')
basepath = '%s/git/%s.git' % (home, repository_name)

print 'Content-type: text/html\n\n'
print_header(requested_object, branch, repository_name)
if not requested_object:
    print_repo_header(branch, repository_name)
print_tree_or_file(basepath, branch, requested_object, repository_name)
print_footer()
"

ssh -T $1@$2 <<xx029EndOfInput
    mkdir -p ~/public_html/__git
    echo "$HTACCESS" > ~/public_html/.htaccess
    ln -sf -T ~/public_html/__git/ ~/git
    echo "$WEBAPP_INDEX" > ~/git/index.py
    echo "$WEBAPP_REPO" > ~/git/repository_info.py
    echo "$GIT_CGI" > ~/git/git.cgi
    chmod 755 ~/git/index.py ~/git/git.cgi ~/git/repository_info.py
    echo "$GIT_HTACCESS" > ~/git/.htaccess
xx029EndOfInput
}


#=== FUNCTION ======================================================
# NAME: init_repo
# DESC: Init git repository on the server
#   $1: repository name
#   $2: remote username
#   $3: remote server
#===================================================================
init_repo() {
    ssh -T $2@$3 <<xx029EndOfInput
    git init --bare ~/git/$1.git > /dev/null
xx029EndOfInput
    echo "ssh:  ssh://$2@$3/~/git/$1.git"
    echo "http: http://$3/~$2/git/$1.git"
}

#=== FUNCTION ======================================================
# NAME: list_repositories
# DESC: List user's repositories
#   $1: remote username
#   $2: remote server
#===================================================================
list_repositories() {
    ssh -T $1@$2 <<xx029EndOfInput
    find ~/git/ -maxdepth 1 -name "*.git" -type d -printf "%f\n" | sed 's/.git$//' | sed 's/.*/\0:\n\tssh:  ssh:\/\/$1@$2\/~\/git\/\0.git\n\thttp: http:\/\/$2\/~$1\/git\/\0.git/'
xx029EndOfInput
}

#=== FUNCTION ======================================================
# NAME: delete_repo
# DESC: Delete git repository on the server
#   $1: repository name
#   $2: remote username
#   $3: remote server
#===================================================================
delete_repo() {
    ssh -T $2@$3 <<xx029EndOfInput
    rm -r ~/git/$1.git
xx029EndOfInput
}

#=== FUNCTION ======================================================
# NAME: handle_list
# DESC: Handles list command
#   $1: remote username
#   $2: remote server
#  $3+: additional OPTIONS
#===================================================================
handle_list() {
    if [ ! $# = 2 ]; then
        show_list_help
        exit 1
    fi
    list_repositories $1 $2
}

#=== FUNCTION ======================================================
# NAME: handle_delete
# DESC: Handles delete command
#   $1: remote username
#   $2: remote server
#  $3+: additional OPTIONS
#===================================================================
handle_delete() {
    if [ $# -lt 3 ]; then
        show_init_help
        exit 1
    fi
    delete_repo $3 $1 $2
}

#=== FUNCTION ======================================================
# NAME: handle_init
# DESC: Handles init command
#   $1: remote username
#   $2: remote server
#  $3+: additional OPTIONS
#===================================================================
handle_init() {
    if [ $# -lt 3 ]; then
        show_init_help
        exit 1
    fi

    init_repo $3 $1 $2
}

#=== FUNCTION ======================================================
# NAME: handle_init_server
# DESC: Handles init-server command
#   $1: remote username
#   $2: remote server
#  $3+: additional OPTIONS
#===================================================================
handle_init_server() {
    if [ ! $# = 2 ]; then
        show_init_server_help
        exit 1
    fi
    init_server $1 $2
}

#=== FUNCTION ======================================================
# NAME: handle_command
# DESC: Handles all commands
#   $1: remote username
#   $2: remote server
#   $3: command
#  $4+: additional OPTIONS
#===================================================================
handle_command() {
    if [ $# -lt 3 ]; then
        show_general_help
        exit 1
    fi
    USER=$1
    HOST=$2
    COMMAND=$3
    shift; shift; shift

    case $COMMAND in
        ls|list)
            handle_list $USER $HOST $@
            ;;
        rm|delete)
            handle_delete $USER $HOST $@
            ;;
        init)
            handle_init $USER $HOST $@
            ;;
        init-server)
            handle_init_server $USER $HOST $@
            ;;
        *)
            show_general_help
            exit 1
    esac
}


COMMAND=$1
case $COMMAND in
    --help)
        shift
        show_help $@
        exit 0
        ;;
    *)
        if [ $# -lt 1 ]; then
            show_general_help
            exit 1
        fi
        IFS="@" read USER HOST <<EOF
$1
EOF
        shift
        if [ ! $USER ] || [ ! $HOST ]; then
            show_general_help
            exit 1
        fi
        handle_command $USER $HOST $@
        exit 0
        ;;
esac
